### ISSUE TITLE
Build from source or some other way to include modules?

### ISSUE THREAD

**Issue by zetas** [sous-chefs/nginx#523]
This isn't so much a bug report as a question, I see this cookbook was able to build from source at some point in the past but that functionality seems to have been removed. Is there any other way to install modules or is it up to me to find/create another cookbook to do source installs? 

I assume since it was taken out people found another way to install modules, or just don't use third party modules I guess? Any help for a newb would be appreciated.

**Comment by MarkGibbons** [comment]
Looking at it.  I think you are correct that folks found some other way to install modules.  This cookbook will install a package including nginx and module but it won't build the package.

**Comment by majormoses** [comment]
Not really what you are looking but figured I'd mention that #552 has been merged and released. This makes it possible to at least specify a different package name which could include additional modules that it was compiled with.

**Comment by ramereth** [comment]
@zetas does #552 resolve this issue for you?

**Comment by zetas** [comment]
@ramereth no, not really, there are still modules that need to be compiled in that aren't included in the -full package. We can close this though, I just went ahead and forked this cookbook and reverted the removal of a source build option.

**Comment by ramereth** [comment]
@zetas ok sounds good. You're welcome to provide a PR which adds this back in a way that works for us. I think in general, we're trying to avoid doing source installations as they tend to break easily after time. However, if this is the only way to provide some functionality for additional modules, we may want to look into this further.

**Comment by majormoses** [comment]
@zetas ya I feel you and can relate as I have worked in shops where we used custom modules. We use to use the compiled option in this cookbook but eventually switched (before the "big break") because it was too costly to compile (which would take ~5 minutes if I am not mistaken) at deploy time. We opted to to create our own package that we added to our nexus and used the unique package name. Just offering you a suggestion and completely understand why that is extra work and not something you may want to do.
